using System;
using MonoSoftware.LLBLGen;
using System.Xml.Serialization;

namespace MonoSoftware.MonoX.DAL.EntityClasses
{
    public partial class AuditInfoEntity : IAuditInfoEntity
    {
        //Note: Implemented as properties generated by LLBLGen
        private ActionData _internalActionData = null;
        [XmlIgnore]
        public ActionData ActionDataLog
        {
            get
            {
                return _internalActionData;
            }
            set
            {
                _internalActionData = value;
            }
        }
    }
}
